### ISSUE TITLE
docker-compose up -d server returns 500 error

### ISSUE THREAD

**Issue by dmdhrumilmistry** [metlo-labs/metlo#127]
I'm trying to use metlo on my local host. I've followed the steps from README. After containers are started when I try to visit the web app, it returns a 500 error.

Do I need to set environment variables? can the team add those instructions to the README?

```bash
$ docker-compose up -d
WARNING: The BACKEND_URL variable is not set. Defaulting to a blank string.
WARNING: The SANDBOX_MODE variable is not set. Defaulting to a blank string.
WARNING: The DISABLE_LOGGING_STATS variable is not set. Defaulting to a blank string.
WARNING: The NUM_WORKERS variable is not set. Defaulting to a blank string.

-- snip --
```

![image](https://user-images.githubusercontent.com/56185972/202543507-e19752fd-f8c3-41e5-93e4-262cf9d5773d.png)

**Comment by akshay288** [comment]
Hey @dmdhrumilmistry ! Sometimes the backend take some time to start up so the frontend service can't connect, we're working on a fix for that... Can you wait for a minute after starting and refresh?

If that doesn't work can you send me your docker logs?

**Comment by dmdhrumilmistry** [comment]
> Hey @dmdhrumilmistry ! Sometimes the backend take some time to start up so the frontend service can't connect, we're working on a fix for that... Can you wait for a minute after starting and refresh?
> 
> If that doesn't work can you send me your docker logs?

thanks for the quick response. Yeah sure, I'll give it a try.

**Comment by dmdhrumilmistry** [comment]
@akshay288 yes its working
