### ISSUE TITLE
Feature Request: Add option to obsfucate PII

### ISSUE THREAD

**Issue by dmdhrumilmistry** [metlo-labs/metlo#140]
Greetings Metlo Team,

Is it possible to store PII information in obfuscated form? This will ensure user privacy.

for example: 

```json
{
"other_params":"...",
"email":"random@domain.xyz",
"phone":"1234567890"
}
```

Obfuscated Form:
```json
{
"other_params":"...",
"email":"raxxxxx@domxxx.xxx",
"phone":"xx3456xxxx"
}
```

**Comment by NikhilShahi** [comment]
Hi @dmdhrumilmistry ,
We do currently have an option to redact select fields so that they are instead stored as `[REDACTED]`. You can do this by editing the Metlo Config section in the Settings page. Here are the docs on how to do so: https://docs.metlo.com/docs/metlo-config

**Comment by dmdhrumilmistry** [comment]
ohh; @NikhilShahi thank you for the information
