### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by matiaslopezd** [metlo-labs/metlo#163]
![chrome-capture-2022-11-2](https://user-images.githubusercontent.com/23618492/205353654-0fe5557a-96e5-44d4-b12a-27879085482c.gif)

I deployed with Docker step by step in a cloud server, following the instructions:

![image](https://user-images.githubusercontent.com/23618492/205354638-c08b7f65-3b85-4323-be58-df4be3056fc5.png)

Devtools network tab show this:

1. `/auth/login` (200 OK - POST) -> JWT
2. `/_next/data/XXXXXXXXXXXX/index.json` (307 Temporary Redirect - GET) -> no response
3. `/_next/data/XXXXXXXXXXXX/login.json` (200 OK - GET) -> 
```js
{
    "pageProps": {
        "localAuthAllowed": true
    },
    "__N_SSP": true
}
```
4. Nothing happens

**Comment by AHarmlessPyro** [comment]
Hi @matiaslopezd , sorry for the issue. 
Can you let me know if you singed up on the docker hosted instance ? The credentials there are separate from my.metlo.com (for security/privacy reasons).

**Comment by akshay288** [comment]
Hey @matiaslopezd Sorry about that! What browser are you using?

**Comment by akshay288** [comment]
Hm strange, can you check if an `authToken` cookie getting set? Also happy to get on a quick zoom if that works, I think it would be faster to debug...

**Comment by akshay288** [comment]
We fixed this issue:

By default all our auth cookies are secure only, they only work when using `https` or `localhost` to access the Web UI. If you are accessing Metlo via `http://<some_ip>` they don't work. We recommend tunneling to Metlo and then using `localhost` but if you are already in a secure network you can add the following to your env file by (`/opt/metlo/.env`):

```
SECURE_AUTH_COOKIE=false
```

Then restart and update metlo with `sudo metlo-deploy update`
