### ISSUE TITLE
Python Django Ingestor Won't Work in Async mode

### ISSUE THREAD

**Issue by dmdhrumilmistry** [metlo-labs/metlo#320]
According to the Django docs, current Django ingestor middleware won't work in asynchronous mode. Consider making changes as per Django doc for asynchronous support: https://docs.djangoproject.com/en/3.2/topics/http/middleware/#asynchronous-support

Example from doc:
```python
import asyncio
from django.utils.decorators import sync_and_async_middleware

@sync_and_async_middleware
def simple_middleware(get_response):
    # One-time configuration and initialization goes here.
    if asyncio.iscoroutinefunction(get_response):
        async def middleware(request):
            # Do something here!
            response = await get_response(request)
            return response

    else:
        def middleware(request):
            # Do something here!
            response = get_response(request)
            return response

    return middleware
```

**Comment by AHarmlessPyro** [comment]
Thanks for the info @dmdhrumilmistry . We'll get a fix in ASAP 😃

**Comment by AHarmlessPyro** [comment]
Hey @dmdhrumilmistry , we've isolated the issue and fixed it. A new build (v 0.0.17) should be up momentarily
