### ISSUE TITLE
Thanks but..!!

### ISSUE THREAD

**Issue by haithem-souala** [metlo-labs/metlo#33]
Hey,

Thanks for making metlo Opensource, i think the future is OSS, but, do you've any plan guys to make a simple version of Protection  feature available in OSS version? that may speed up the adoption of the product.

**Comment by shrisukhani** [comment]
Hey @haithem-souala -- thanks for reaching out and sorry about the late reply!

We don't have any immediate plans to open source the protection feature right now. Will keep you posted if/when we do go in that direction 🙂
