### ISSUE TITLE
Request: vanilla net/http ingestion connextion example for golang

### ISSUE THREAD

**Issue by jmandel1027** [metlo-labs/metlo#422]
Hey gang,

very cool stuff happening here! I was looking over the docs for the ingestion connections in go and would love to see an example of it with the vanilla net/http handler middleware usage I'm sure the broader community would appreciate it, it's a very commonly used pattern, [here's a nice example ](https://www.alexedwards.net/blog/making-and-using-middleware) thats compatible with any service using the stdlib for their server.

Great stuff here, looking forward to following this project!

**Comment by jmandel1027** [comment]
oh wait never mind, the [gorrilla one is all stdlib](https://github.com/metlo-labs/metlo/blob/develop/ingestors/golang/gorilla/metlo_gorilla.go). Just confused me for a second since the [docs](https://docs.metlo.com/connections/go#setup) used the `r.Use()`  for mounting the middleware

**Comment by AHarmlessPyro** [comment]
Hey @jmandel1027, no problems !
It's always awesome to see people using Metlo and thinking of bettering it. Feel free to let us know how else we could make Metlo work better for you and your use case.
