### ISSUE TITLE
[Bug] Too many false-positive

### ISSUE THREAD

**Issue by Drjacky** [metlo-labs/metlo#50]
I tried it on my Android repo but, almost all of the issued cases were false-positive. For example https://github.com/Drjacky/MVIModularizationTemplate/issues/19

It says there is an issue with `kotlin-stdlib-1.4.31.jar` but, neither my repo nor the internal library(root dependency) use that version:
<img width="403" alt="Screen Shot 2022-10-25 at 17 34 31" src="https://user-images.githubusercontent.com/2296754/197831871-3c7c02b1-a67d-4ebc-9ec7-45a9d131abb4.png">

Third-library: https://github.com/detekt/sarif4k/blob/main/build.gradle.kts

**Comment by Drjacky** [comment]
As you see, they have updated from 1.4.31 on 29th April, 2022: https://github.com/detekt/sarif4k/commit/bb1c8204aed9b176cd4f7143db8ec08fdde5e0fa

**Comment by shrisukhani** [comment]
Hey @Drjacky — I think you found the wrong repo? This doesn’t look like a Metlo issue :)
