### ISSUE TITLE
Missing endpoint in Node Agent

### ISSUE THREAD

**Issue by Killian-G** [metlo-labs/metlo#87]
Hi! With the nodejs agent when the `POST` request is sent to the metlo backend from nodejs agent the endpoint `/api/v1/log-request/single` is missing, so the current workaround is to add `/api/v1/log-request/single` to the host URL

**Comment by AHarmlessPyro** [comment]
Thanks for the heads up @Killian-G. We'll have a fix for this issue asap.

**Comment by AHarmlessPyro** [comment]
Thanks @Killian-G , we've updated the metlo agent for Node with the bugfix. You should be able to use it just by supplying the collector url without the endpoint information.
