### ISSUE TITLE
AMI Request - AWS Sydney Region

### ISSUE THREAD

**Issue by bconolly** [metlo-labs/metlo#95]
Hi Metlo team, what a fantastic project! I'd just like to put in a request for an AMI in the AWS Sydney Region please and keep up the great work!

**Comment by shrisukhani** [comment]
Hey @bconolly, thanks for the kind words! Working on it now, will have it done in a bit!

**Comment by akshay288** [comment]
@bconolly the image is ready here: https://backend.metlo.com/deploy/aws?region=ap-southeast-2

**Comment by bconolly** [comment]
> @bconolly the image is ready here: https://backend.metlo.com/deploy/aws?region=ap-southeast-2
> 
> Let us know if you need anything else!

Thanks very much!
