### ISSUE TITLE
What is <YOUR_METLO_COLLECTOR_URL> ?

### ISSUE THREAD

**Issue by ZeRego** [metlo-labs/metlo#97]
Hi there 👋 

I setup Metlo locally using docker compose ( read me instructions ). 

```
git clone https://github.com/metlo-labs/metlo.git
cd metlo
ENCRYPTION_KEY="some random string" EXPRESS_SECRET="some random string" docker-compose up -d
```

I'm also running my local app via docker compose and followed your intructions for a node connection.

```
var metlo = require("metlo")
metlo(<YOUR_METLO_API_KEY>, <YOUR_METLO_COLLECTOR_URL>)
```

### First problem/question
Can't find in your docs what the `YOUR_METLO_COLLECTOR_URL` should be. 
From looking at your docker compose file it looks like **collector** is also an alias for **injestor** and looking at the node library the value expected is just the host. 
Not sure if I can just pass the host or also need to include the port for the injestor (8081).

Suggestion:
- update names to be consistent
- show the `YOUR_METLO_COLLECTOR_URL` value when the user is on the connections page or when creating a key

### Second problem/question

Since I'm running both apps in docker I can't point to localhost. I tried using `http://host.docker.internal` but without success. Do you know what I should set as the `YOUR_METLO_COLLECTOR_URL` in my case?

**Comment by AHarmlessPyro** [comment]
HI @ZeRego 
`YOUR_METLO_COLLECTOR_URL` refers a URL that is accessible to a metlo ingestor. Since you're using the docker compose method, by default it should be exposing the collector at `http://localhost:8081`. You can test if it's accessible by performing a GET request to `http://localhost:8081/api/v1`, and if it's working correctly, then it should respond with a 200 OK response. 
```bash
curl --location --request GET 'http://localhost:8081/api/v1'
```

So, while running on docker for local applications, you should be able to use `http://localhost:8081` as the collector url. 

Thanks for your suggestions. We still have to make our docs better and surface information to users more intuitively 😅

**Comment by ZeRego** [comment]
Running that curl from my machine returns a 200.
Running that curl from the docker container, where my app runs, doesn't return 200

```
# curl --location --request GET 'http://localhost:8081/api/v1'
curl: (7) Failed to connect to localhost port 8081: Connection refused
```

```
# curl --location --request GET 'http://host.docker.internal:8081'
Client unauthorized
```


![Nov-10-2022 11-11-19](https://user-images.githubusercontent.com/9117144/201076396-bc7f30a5-e0ad-448d-bc64-6a98859ef14d.gif)

**Comment by ZeRego** [comment]
> The issue here is that you require some way of collecting data from the container that you want to monitor.

We already have that part. You can check my commit and branch:
https://github.com/lightdash/lightdash/commit/226ddd0b4c3531aca1d3fc0a7534230470089e3a

I double checked the env variables are correct and I get the log:
`2022-11-10 16:05:47 [Lightdash] info: Started Metlo connection: http://host.docker.internal:8081`

**Comment by ZeRego** [comment]
> What you could try is running something like this :

Running that curl from my container worked and I can see the Metlo dashboard updated. That means the key and host are correct and the problem must be in my code or in the metlo library. 🤔

**Comment by AHarmlessPyro** [comment]
> > The issue here is that you require some way of collecting data from the container that you want to monitor.
> 
> We already have that part. You can check my commit and branch: [lightdash/lightdash@226ddd0](https://github.com/lightdash/lightdash/commit/226ddd0b4c3531aca1d3fc0a7534230470089e3a)
> 
> I double checked the env variables are correct and I get the log: `2022-11-10 16:05:47 [Lightdash] info: Started Metlo connection: http://host.docker.internal:8081`

My bad, I didn't notice that you were running on node. I have amended the response as such. 

As for the second thing,

> > What you could try is running something like this :
> 
> Running that curl from my container worked and I can see the Metlo dashboard updated. That means the key and host are correct and the problem must be in my code or in the metlo library. 🤔

Looking at the commit you mentioned, can you try importing metlo before express ? I think that's the issue here. Metlo ingestor needs to intercept traces in express and to properly capture those, we need metlo to be imported before express is.

**Comment by ZeRego** [comment]
>  Metlo ingestor needs to intercept traces in express and to properly capture those, we need metlo to be imported initialized before express is imported.

That doesn't seem code friendly😞
We have eslint rule `import/first` to have all the imports at the top and then the executable code. So that would require us to disable eslint for those lines or change our file structure to guarantee express is only imported afterwards.
It would be great if there was an `express-metlo` package that was initialized like other express plugins. 
```
const app = express();
app.use(metlo);
...
```

After disabling the eslint I was able to get just 2 requests, out hundreds, logged in Metlo. And I can see that is not picking up the correct route paths. 
First request shows the path '/health' when the full path is '/api/v1/health'
Second request shows the path `/` when the full path is `'/api/v1/user/'

We have our routes broken down across multiple files so I suppose you only pick the last part of the path.
Example:
```
// index.ts
const app = express();
app.use('/api/v1', apiV1Router);

// apiV1.ts
export const apiV1Router = express.Router();
apiV1Router.use('/user', userRouter);

// user.ts
export const userRouter = express.Router();
userRouter.get('/', (req, res) => {
 ...
});
```

**Comment by akshay288** [comment]
Hey @ZeRego sorry about that! We have a fix ready here: #101 . I'll let you know when we deploy the new version. Apologies again for the back and forth, that was a really dumb bug... We're fairly new so we're still ironing out the quirks.

Also, thanks for all the feedback! We'll incorporate it all in our docs and setup process in the next few days...

**Comment by akshay288** [comment]
Also I'd love to get on a call to get any other feedback you have :) Let me know if you'd be up for it!

**Comment by AHarmlessPyro** [comment]
Hey @ZeRego, We've updated our metlo package, and it should be able to capture all the routes. Let us know if there are any other issues you encounter. We'll do our best to fix them asap 😃

**Comment by AHarmlessPyro** [comment]
Hey @ZeRego, let us know if there's any other ways we can help you or improve metlo. In the meantime, I'll be closing this issue.
