### ISSUE TITLE
Daemonset is unable to start

### ISSUE THREAD

**Issue by venkateshmadala** [metlo-labs/metlo#99]
We are seeing below error when we try to install metlo daemonset on K8S cluster.
I can see similar issue on https://github.com/metlo-labs/metlo/issues/52#issuecomment-1296806302 
Can you share solution.

STARTING
starting suricata
starting metlo
10/11/2022 -- 19:26:26 - <Notice> - This is Suricata version 6.0.1 RELEASE running in SYSTEM mode
10/11/2022 -- 19:26:26 - <Warning> - [ERRCODE: SC_ERR_SYSCALL(50)] - Failure when trying to get MTU via ioctl for 'eth0': No such device (19)
10/11/2022 -- 19:26:26 - <Warning> - [ERRCODE: SC_ERR_SYSCALL(50)] - Failure when trying to get MTU via ioctl for 'eth0': No such device (19)
10/11/2022 -- 19:26:26 - <Warning> - [ERRCODE: SC_ERR_SOCKET(200)] - Error connecting to socket "/tmp/eve.sock": Connection refused (will keep trying)
10/11/2022 -- 19:26:26 - <Notice> - JsonRdpLog logger not enabled: protocol rdp is disabled
10/11/2022 -- 19:26:26 - <Notice> - JsonIKEv2Log logger not enabled: protocol ikev2 is disabled
10/11/2022 -- 19:26:26 - <Notice> - JsonKRB5Log logger not enabled: protocol krb5 is disabled
10/11/2022 -- 19:26:26 - <Notice> - JsonSNMPLog logger not enabled: protocol snmp is disabled
10/11/2022 -- 19:26:26 - <Notice> - JsonRFBLog logger not enabled: protocol rfb is disabled
10/11/2022 -- 19:26:26 - <Error> - [ERRCODE: SC_ERR_STATS_LOG_GENERIC(278)] - eve.stats: stats are disabled globally: set stats.enabled to true. See https://suricata.readthedocs.io/en/suricata-6.0.1/configuration/suricata-yaml.html#stats
10/11/2022 -- 19:26:27 - <Error> - [ERRCODE: SC_ERR_AFP_CREATE(190)] - Unable to find type for iface "eth0": No such device
10/11/2022 -- 19:26:27 - <Notice> - all 2 packet processing threads, 2 management threads initialized, engine started.
10/11/2022 -- 19:26:27 - <Error> - [ERRCODE: SC_ERR_AFP_CREATE(190)] - Unable to find iface eth0: No such device
10/11/2022 -- 19:26:27 - <Error> - [ERRCODE: SC_ERR_AFP_CREATE(190)] - Couldn't init AF_PACKET socket, fatal error
10/11/2022 -- 19:26:27 - <Error> - [ERRCODE: SC_ERR_FATAL(171)] - thread W#01-eth0 failed

**Comment by akshay288** [comment]
Hey @venkateshmadala ! Sorry about that... Can you try running `ip link` in the instance and send the result? You might have to `apt install iproute2` first...

Also happy to debug this in our [discord](https://discord.gg/4xhumff9BX) :)

**Comment by venkateshmadala** [comment]
Here is the response @akshay288 
Can you share Discord invite. 

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 02:21:11:2b:81:6c brd ff:ff:ff:ff:ff:ff
    altname enp0s5
3: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 8981 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
8: cali18e7f0fa532@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8981 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 129d85a7-c12c-48c2-9015-e98c8d4fde6d
26: cali11b4497d806@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8981 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns 4dd584ee-b59a-4e31-bdd1-8d7832c935e8

**Comment by AHarmlessPyro** [comment]
Hey @venkateshmadala, let us know if there's any other ways we can help you or improve metlo. In the meantime, I'll be closing this issue.
